server:
  port: 8088
siriusrpc:
  providers: http://localhost:8081,http://localhost:8082
  zkServer: localhost:2181
  zkRoot: siriusrpc

app:
  id: app1
  namespace: public
  env: dev
  retries: 2
  timeout: 1000

logging:
  level:
    root: info
    org.galaxy.siriusrpc: debug

