server:
  port: 8081

app:
  id: app1
  namespace: public
  env: dev
  metas: "{gray: 'false', dc: 'bj', unit: 'B001'}"

siriusrpc:
  zkServer: localhost:2181
  zkRoot: siriusrpc

logging:
  level:
    root: error
    org.galaxy.siriusrpc: info
